services:
  mocks:
    build: .
    container_name: badge-sensor-mock
    environment:
      - MQTT_BROKER_HOST=192.168.248.130
      - MQTT_BROKER_PORT=1883
      - MQTT_TOPIC=sensor/data
    networks:
      - paas-network

networks:
  paas-network:
    external: true
