services:
  redis-cache:
    image: redis:8
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - data:/data

  core-operational-backend:
    build: ./core-operational-backend
    container_name: core-operational-backend
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 192.168.248.103:9092
      SPRING_DATA_REDIS_HOST: redis-cache
      SPRING_DATA_REDIS_PORT: 6379
    ports:
      - "8080:8080"
    depends_on:
      - redis-cache

volumes:
  data: