services:
  entrance-cockpit-backend:
    build: .
    container_name: entrance-cockpit-backend
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 172.31.252.29:9092
    ports:
      - "8087:8087"