services:
  badge-sensor-mock:
    build: badge-sensor-mock
    container_name: badge-sensor-mock
    environment:
      - MQTT_BROKER_HOST=172.31.249.144
      - MQTT_BROKER_PORT=8883
      - MQTT_BADGE_TOPIC=sensor/data
  entrance-door-lock:
    build: entrance-door-lock
    container_name: entrance-door-lock
    environment:
      - MQTT_BROKER_HOST=172.31.249.144
      - MQTT_BROKER_PORT=8883
      - MQTT_DOOR_TOPIC=door/open