version: '3.8'
services:
  cache-loader:
    build: ./cache-loading-backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://34.155.209.62:5432/registered_people
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: s:Nvt:<M;+L{}3tJ
      REDIS_HOST: 192.168.248.120
      REDIS_PORT: 6379
      TZ: Europe/Paris
      JAVA_TOOL_OPTIONS: "-Duser.timezone=Europe/Paris"
      # Autres variables d'environnement Spring Boot si nécessaire
    ports:
      - "8080:8080" # Spring Boot utilise le port 8080 par défaut
    # Ajoutez un healthcheck pour une robustesse accrue (optionnel mais recommandé)
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"] # Nécessite Spring Boot Actuator
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s # Temps pour le démarrage initial de l'application

volumes:
  db_data:

networks:
  paas-network:
    external: true