services:
  telemetry-to-messaging-backend:
    build: .
    container_name: telemetry-to-messaging-backend
    environment:
      - MQTT_BROKER_HOST=192.168.248.130
      - MQTT_BROKER_PORT=1883
      - MQTT_TOPIC=sensor/data
    ports:
      - "8085:8085"
    networks:
      - paas-network

networks:
  paas-network:
    external: true
