services:
  entrance-cockpit-backend:
    build: entrance-cockpit-backend
    container_name: entrance-cockpit-backend
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 192.168.248.103:9092
      SPRING_DATASOURCE_URL: jdbc:postgresql://34.155.209.62:5432/registered_people
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: s:Nvt:<M;+L{}3tJ
    ports:
      - "8087:8087"
  static-server-backend:
    build:
      context: static-server-backend
      args:
        VITE_WS_URL: "wss://172.31.249.144/entrance/ws"
    container_name: static-server-backend
    ports:
      - "5173:80"
