services:
  entrance-cockpit-backend:
    build: entrance-cockpit-backend
    container_name: entrance-cockpit-backend
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 192.168.248.103:9092
      SPRING_DATASOURCE_URL: jdbc:postgresql://192.168.248.101:5432/registered_people
      SPRING_DATASOURCE_USERNAME: dbuser
      SPRING_DATASOURCE_PASSWORD: dbpassword
    ports:
      - "8087:8087"
  static-server-backend:
    build: static-server-backend
    container_name: static-server-backend
    ports:
      - "5173:80"