services:
  entrance-door-lock:
    build: .
    container_name: entrance-door-lock
    environment:
      - MQTT_BROKER_HOST=192.168.248.130
      - MQTT_BROKER_PORT=1883
      - MQTT_DOOR_TOPIC=door/open
